"""
Customer Review MongoDB Document

Stores normalized customer-experience reviews.

Responsibilities:

- Preserve tenant scope by business_id.
- Support deterministic deduplication when an external review ID
  is unavailable.
- Preserve information-quality and meaningfulness classifications.
- Store only minimized normalized raw data.
"""

from datetime import UTC, datetime
from typing import Any, Literal
from uuid import UUID

from beanie import Document
from pydantic import Field
from pymongo import ASCENDING, DESCENDING, IndexModel


# ============================================================
# Customer Review Document
# ============================================================
class CustomerReviewDocument(Document):
    """
    One normalized customer-experience review.

    A customer review belongs to exactly one business and exactly
    one customer-voice source.

    deduplication_key is generated by the storage service:

    - External review ID when available.
    - Deterministic SHA-256 identity when no external ID exists.
    """

    business_id: UUID

    source: Literal[
        "google_maps",
        "facebook_comments",
        "facebook_reviews",
        "instagram_comments",
        "linkedin_comments",
        "tiktok_comments",
        "website_reviews",
        "other",
    ]

    source_review_id: str | None = None

    deduplication_key: str = Field(
        min_length=1,
        max_length=128,
    )

    text: str = Field(
        min_length=1,
    )

    language: str | None = None

    rating: float | None = Field(
        default=None,
        ge=0,
        le=5,
    )

    published_at: datetime | None = None

    collected_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

    information_quality: Literal[
        "high",
        "medium",
        "low",
    ]

    is_meaningful: bool

    is_emoji_only: bool = False

    raw_data: dict[str, Any] = Field(
        default_factory=dict,
    )

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

    # ========================================================
    # Beanie Settings and MongoDB Indexes
    # ========================================================
    class Settings:
        name = "customer_reviews"

        indexes = [
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("source", ASCENDING),
                    ("deduplication_key", ASCENDING),
                ],
                name=(
                    "uq_customer_reviews_"
                    "business_source_dedup"
                ),
                unique=True,
            ),
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("published_at", DESCENDING),
                ],
                name=(
                    "ix_customer_reviews_"
                    "business_published_at"
                ),
            ),
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("information_quality", ASCENDING),
                ],
                name=(
                    "ix_customer_reviews_"
                    "business_quality"
                ),
            ),
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("is_meaningful", ASCENDING),
                ],
                name=(
                    "ix_customer_reviews_"
                    "business_meaningful"
                ),
            ),
        ]

    def __repr__(self) -> str:
        return (
            f"<CustomerReview "
            f"{self.source}:"
            f"{self.source_review_id or self.deduplication_key} "
            f"business={self.business_id}>"
        )