"""
Social Comment MongoDB Document

Stores normalized comments collected from social-media platforms.

Responsibilities:

- Preserve business and social-account tenant scope.
- Link each comment to its internal MongoDB social post.
- Preserve platform comment identity when available.
- Support deterministic deduplication when an external comment ID
  is unavailable.
- Preserve information-quality and emoji-only classifications.
- Store only minimized normalized raw data.
"""

from datetime import UTC, datetime
from typing import Any, Literal
from uuid import UUID

from beanie import Document, PydanticObjectId
from pydantic import Field
from pymongo import ASCENDING, DESCENDING, IndexModel


# ============================================================
# Social Comment Document
# ============================================================
class SocialCommentDocument(Document):
    """
    One normalized social-media comment.

    A comment belongs to exactly one business, social account,
    platform post, and internal MongoDB social-post document.

    deduplication_key is generated by the storage service:

    - External comment ID when available.
    - Deterministic SHA-256 identity when no external ID exists.
    """

    business_id: UUID

    social_account_id: UUID

    social_post_id: PydanticObjectId

    platform: Literal[
        "facebook",
        "instagram",
        "linkedin",
        "tiktok",
        "youtube",
        "other",
    ]

    platform_post_id: str = Field(
        min_length=1,
    )

    platform_comment_id: str | None = None

    deduplication_key: str = Field(
        min_length=1,
        max_length=128,
    )

    text: str = Field(
        min_length=1,
    )

    published_at: datetime | None = None

    like_count: int | None = Field(
        default=None,
        ge=0,
    )

    reply_count: int | None = Field(
        default=None,
        ge=0,
    )

    author_reference: str | None = None

    information_quality: Literal[
        "high",
        "medium",
        "low",
    ]

    is_emoji_only: bool = False

    connector_type: str = Field(
        min_length=1,
    )

    raw_data: dict[str, Any] = Field(
        default_factory=dict,
    )

    collected_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(
            UTC,
        ),
    )

        # ========================================================
    # Beanie Settings and MongoDB Indexes
    # ========================================================
    class Settings:
        name = "social_comments"

        indexes = [
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("social_account_id", ASCENDING),
                    ("platform", ASCENDING),
                    ("deduplication_key", ASCENDING),
                ],
                name=(
                    "uq_social_comments_"
                    "tenant_platform_dedup"
                ),
                unique=True,
            ),
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("published_at", DESCENDING),
                ],
                name=(
                    "ix_social_comments_"
                    "business_published_at"
                ),
            ),
            IndexModel(
                [
                    ("social_post_id", ASCENDING),
                    ("published_at", DESCENDING),
                ],
                name=(
                    "ix_social_comments_"
                    "post_published_at"
                ),
            ),
            IndexModel(
                [
                    ("business_id", ASCENDING),
                    ("information_quality", ASCENDING),
                ],
                name=(
                    "ix_social_comments_"
                    "business_quality"
                ),
            ),
        ]

    def __repr__(self) -> str:
        return (
            f"<SocialComment "
            f"{self.platform}:"
            f"{self.platform_comment_id or self.deduplication_key} "
            f"business={self.business_id}>"
        )