"""add social accounts

Revision ID: 5e2d0624c669
Revises: 52c8ad7d4d8f
Create Date: 2026-07-14 11:15:19.152671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e2d0624c669'
down_revision: Union[str, Sequence[str], None] = '52c8ad7d4d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_username', sa.String(length=255), nullable=True),
    sa.Column('account_url', sa.String(length=1000), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('credential_reference', sa.String(length=500), nullable=True),
    sa.Column('account_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_account_id', name='uq_social_accounts_platform_account')
    )
    op.create_index(op.f('ix_social_accounts_business_id'), 'social_accounts', ['business_id'], unique=False)
    op.create_index('ix_social_accounts_business_platform', 'social_accounts', ['business_id', 'platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_accounts_business_platform', table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_business_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
