"""
Initiative Model
Strategic initiatives generated by the Strategy Agent.
"""
from datetime import datetime, date
from uuid import UUID, uuid4
from decimal import Decimal

from sqlalchemy import Date, DateTime, ForeignKey, Integer, Numeric, String
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.postgres import Base


class Initiative(Base):
    """
    Strategic initiative tracking.
    
    Examples:
    - "Launch Premium Loyalty Program"
    - "Build Competitor Review Dataset"
    """
    __tablename__ = "initiatives"

    # ========================================================
    # Primary Key
    # ========================================================
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )

    # ========================================================
    # Foreign Keys
    # ========================================================
    business_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    strategy_report_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("reports.id"),
        nullable=True,
    )
    assigned_to: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )

    # ========================================================
    # Initiative Info
    # ========================================================
    initiative_id_external: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        # e.g. "INIT_SO_food_01"
    )
    title: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )
    strategy_type: Mapped[str | None] = mapped_column(
        String(10),
        nullable=True,
        # SO, ST, WO, WT, FOUNDATIONAL
    )

    # ========================================================
    # Status & Progress
    # ========================================================
    status: Mapped[str] = mapped_column(
        String(30),
        default="pending",
        # pending, in_progress, completed, cancelled
    )
    progress_percent: Mapped[int] = mapped_column(
        Integer,
        default=0,
    )

    # ========================================================
    # Scoring
    # ========================================================
    priority_score: Mapped[Decimal | None] = mapped_column(
        Numeric(4, 2),
        nullable=True,
    )
    priority_tier: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        # must_do, should_do, nice_to_have
    )
    impact_score: Mapped[Decimal | None] = mapped_column(
        Numeric(3, 1),
        nullable=True,
    )
    feasibility_score: Mapped[Decimal | None] = mapped_column(
        Numeric(3, 1),
        nullable=True,
    )
    urgency_score: Mapped[Decimal | None] = mapped_column(
        Numeric(3, 1),
        nullable=True,
    )

    # ========================================================
    # Execution
    # ========================================================
    timeline: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        # short, medium, long
    )
    budget_tier: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        # low, medium, high
    )
    due_date: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
    )

    # ========================================================
    # Extra metadata
    # ========================================================
    initiative_metadata: Mapped[dict] = mapped_column(
        JSONB,
        default=dict,
    )

    # ========================================================
    # Timestamps
    # ========================================================
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ========================================================
    # Relationships
    # ========================================================
    business: Mapped["Business"] = relationship(
        "Business",
        back_populates="initiatives",
    )

    def __repr__(self) -> str:
        return f"<Initiative {self.title[:30]}... status={self.status}>"